site_name: Serverless on Google Cloud
site_url: https://github.com/cc4i/multi-serverless/
nav:
  - Home: 'index.md'
  - 'General':
    - 'Preparing Cloud Run for Production': general/prepare-run.md
  - 'Solutions':
    - 'Migrate Microservices from GKE to Cloud Run': 'solutions/gke-to-run.md'
  - 'Applications':
    - 'Smart application with Cloud Run': 'applications/run-ai.md'
  - 'Security':
    - 'Handle Auth for Cloud Run by ESPv2': 'security/espv2-run.md'
  - About:
    - 'License': 'license.md'
    - 'Release Notes': 'release-notes.md'
theme: 
  name: material