site_name: Serverless on Google Cloud
site_url: https://github.com/cc4i/multi-serverless/
nav:
  - Home: '../README.md'
  - 'General':
    - 'Preparing Cloud Run for Production': general/prepare-run.md
  - About:
    - 'License': '../LICENSE'
    - 'Release Notes': 'release-notes.md'
theme: 
  name: material