site_name: Serverless on Google Cloud
site_url: https://github.com/cc4i/multi-serverless/
nav:
  - Home: 'index.md'
  - 'General':
    - 'Preparing Cloud Run for Production': general/prepare-run.md
  - About:
    - 'License': 'license.md'
    - 'Release Notes': 'release-notes.md'
theme: 
  name: material